# Generated by Django 5.1.3 on 2025-05-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_coupon_code_order_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('Stripe', 'Stripe')], max_length=100),
        ),
    ]
